# Global settings
[build]
  base = ""
  publish = "dist/"
  command = "npm run build"
  environment = { NODE_VERSION = "16.0.0", NPM_FLAGS = "--version" }
  functions = "functions/"
  ignore = "git diff --quiet HEAD^ HEAD ../../:"

# Deployment settings
[context.production.environment]
  NODE_ENV = "production"
  API_URL = "https://api.example.com"

[context.deploy-preview]
  command = "npm run build:preview"

[context.branch-deploy]
  command = "npm run build:staging"
  environment = { NODE_ENV = "staging" }

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301
  force = true

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Asset optimization
[build.processing]
  skip_processing = false
  css_opt_bundle = true
  js_opt_bundle = true
  js_opt_minify = true
  html_opt_minify = true
  images_opt_minify = true
  images_opt_lossless = true
  svg_opt_minify = true

# Plugin configuration
[[plugins]]
  package = "netlify-plugin-lighthouse"
  [plugins.inputs]
    audits = ['accessibility', 'performance', 'seo']

# Build hooks
[build.lifecycle]
  onBuild = ["echo 'Building project...'"
  onSuccess = ["echo 'Build successful!'", "curl -X POST https://example.com/webhook"]
  onFailure = ["echo 'Build failed!'", "curl -X POST https://example.com/error-webhook"]